title: Meghana Sunil
name: "Meghana's Portfolio"
author: Meghana Sunil
twitter_username: 
baseurl: "/"
description: Machine Learning Research | Domain Generalization | Multimodal Learning
profile_url: "https://github.com/meghanaasunil"
permalink: /:title
show_drafts: false
future: false
category: "post"
img: ""


# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-twitter-plugin
exclude:
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
sass:
  sass_dir: _sass
